name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: ['1.18', '1.17']

    name: Go ${{ matrix.go }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Test and build
      run: |
        go test -race ./...

  format:
    runs-on: ubuntu-latest

    name: Format check

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: Ensure no formatting changes
      run: |
        go fmt ./...
        git diff --exit-code
